fi_bootstrapdemo_index:
    path:  /
    defaults: { _controller: "BootstrapitaliaBundle:Bootstrap:index" }

fi_bootstrapdemo_dropdown:
    path:  /dropdwon
    defaults: { _controller: "BootstrapitaliaBundle:Bootstrap:dropdown" }
